# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 17:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'IOS')], default='android', max_length=20)),
                ('code', models.TextField()),
                ('state', models.CharField(max_length=256)),
                ('auth_token', models.TextField(blank=True, editable=False, null=True)),
                ('social_data', models.TextField(blank=True, editable=False, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=25, null=True, validators=[django.core.validators.RegexValidator(message=b'Data must be entered in Alphabets only.', regex=b'$|[a-zA-Z ]+')])),
                ('last_name', models.CharField(blank=True, default='', max_length=25, null=True, validators=[django.core.validators.RegexValidator(message=b'Data must be entered in Alphabets only.', regex=b'$|[a-zA-Z ]+')])),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('profile_pic_link', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_employer', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('join_date_last_employer', models.DateField(blank=True, null=True)),
                ('connections', models.IntegerField(blank=True, default=500, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_linkedin_profile',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google Plus')], default='google', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'IOS')], default='android', max_length=20)),
                ('social_data', models.TextField(blank=True, editable=False)),
                ('platform_token', models.TextField(blank=True, editable=False)),
                ('session_token', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('imei', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b'Data must be entered in Digits only.', regex=b'[0-9]+')])),
                ('app_registration_id', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google Plus')], default='google', max_length=20)),
                ('platform_id', models.CharField(max_length=256)),
                ('first_name', models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator(message=b'Data must be entered in Alphabets only.', regex=b'$|[a-zA-Z ]+')])),
                ('last_name', models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator(message=b'Data must be entered in Alphabets only.', regex=b'$|[a-zA-Z ]+')])),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Other', b'Other')], default=b'Male', max_length=20)),
                ('profile_link', models.URLField()),
                ('profile_pic_link', models.URLField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_social_profile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='socialprofile',
            unique_together=set([('email_id', 'platform')]),
        ),
    ]
