# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('customer_alternate_email', 'customer_alternate_email'), ('customer_profession_email', 'customer_profession_email')], default='customer_alternate_email', max_length=50)),
                ('verification_code', models.CharField(blank=True, default=messenger.models.random_code32, max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('times', models.IntegerField(blank=True, default=1, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'db_table': 'email_verification',
            },
        ),
    ]
